

out_dir: 'cl20170622_TRIP_CRISPR'

input_file:
  mapping:
    idx_A:
      - [/home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-A_TAGTATCAGC_R1.fastq, /home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-A_TAGTATCAGC_R2.fastq]
      - 10
    idx_B:
      - [/home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-B_TCTCTATGCG_R1.fastq, /home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-B_TCTCTATGCG_R2.fastq]
      - 10
  mutation:
    idx_C:
      - /home/NFS/users/r.schep/projects/RSTP2/20170619_RSTP2_100-4491/RSTP2_100_Idx-C_CGAGAGATAC_R1.fastq
      - 10
      - idx_A

structure:
  mapping: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   %i      -       const   present False   fixed   -
    map_pat1a       GTCACAAGGGCCGGC   -       const   present False   fixed   -
    const_bar       CACAA\{16\}TGATC  -       const_bar       present False   fixed   -
    rev_map_complement      -       TTAACCCTAGAAAGATAATCATATTGTGACGTAC      const   -       False   var   -
    rev_map GTACGTCACAATATGATTATCTTTCTAGGGTTAA      -       const   present True    fixed   -
    fwd_map_complement      -       GATCA[BC]CTCGAGTTGTGGCCGGCCCTTGTGAC     const_bar_comp  -       True    var   -
  mutation: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   %i      -       const   present False   fixed   -
    pat1       GTCACAAGGGCCGGCCACAA   -       const   present False   fixed   -
    barcode 16 - barcode present False fixed -
    pat2       TGATCGGT  -       const       present False   fixed   -

lev_dist: 2

min_count:
    mapping: 3
    mutation: 0

bowtie:
  index:  /home/NFS/users/r.schep/data/bowtie2/hg38/hg38
  options:
      '1': ['--very-sensitive']
      '2': ['--very-sensitive-local']
max_dist:
  '1': 500
  '2': 20

crispr_target: 'GCCGATGGTGAAGTGGTAAG'
crispr_gap: 10
spacer_list: ['GATTATG', 'CACTTT']
gap_list: [94, 88]
